//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaManagement.API.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzaManagement.API.Infrastructure.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address City should not be empty and should be less than or equal to 15 characters..
        /// </summary>
        public static string AddressCity {
            get {
                return ResourceManager.GetString("AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Already Exists.
        /// </summary>
        public static string AddressConflict {
            get {
                return ResourceManager.GetString("AddressConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Country should not be empty and should be less than or equal to 15 characters..
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Description Not Correct Length.
        /// </summary>
        public static string AddressDescription {
            get {
                return ResourceManager.GetString("AddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not Found.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Region Not Correct Length.
        /// </summary>
        public static string AddressRegion {
            get {
                return ResourceManager.GetString("AddressRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Error Occured.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Already Exists.
        /// </summary>
        public static string OrderConflict {
            get {
                return ResourceManager.GetString("OrderConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Not Found.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Pizzas should not be empty..
        /// </summary>
        public static string OrderPizzaList {
            get {
                return ResourceManager.GetString("OrderPizzaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Calory count should be greater than 0..
        /// </summary>
        public static string PizzaCaloryCount {
            get {
                return ResourceManager.GetString("PizzaCaloryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Already Exists.
        /// </summary>
        public static string PizzaConflict {
            get {
                return ResourceManager.GetString("PizzaConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Lenth Is Not Correct.
        /// </summary>
        public static string PizzaDescription {
            get {
                return ResourceManager.GetString("PizzaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Name should be between 3 and 20 characters..
        /// </summary>
        public static string PizzaName {
            get {
                return ResourceManager.GetString("PizzaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Not Found.
        /// </summary>
        public static string PizzaNotFound {
            get {
                return ResourceManager.GetString("PizzaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Price should be greater than 0..
        /// </summary>
        public static string PizzaPizza {
            get {
                return ResourceManager.GetString("PizzaPizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank should be between 1 and 10..
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank History Already Exists.
        /// </summary>
        public static string RankHistoryConflict {
            get {
                return ResourceManager.GetString("RankHistoryConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank History Not Found.
        /// </summary>
        public static string RankHistoryNotFound {
            get {
                return ResourceManager.GetString("RankHistoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Exists.
        /// </summary>
        public static string UserConflict {
            get {
                return ResourceManager.GetString("UserConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email should not be empty and should be in a valid format..
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Firstname should be between 2 and 20 characters..
        /// </summary>
        public static string UserFirstname {
            get {
                return ResourceManager.GetString("UserFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Lastname should be between 2 and 30 characters..
        /// </summary>
        public static string UserLastname {
            get {
                return ResourceManager.GetString("UserLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Phone number should not be empty and should be in a valid format..
        /// </summary>
        public static string UserPhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber", resourceCulture);
            }
        }
    }
}
